Task_1_2
Sharapov-Maksim/OOP_Sharapov_M pull request #2
Opened 2020-10-12 14:40 UTC by Sharapov-Maksim

2020-10-15 17:30 UTC, vlitomsk requested changes
Замечания нужно исправить.

2020-10-15 17:30 UTC, vlitomsk commented on task_1_2/src/main/java/Main.java
> +            char[] strForSearch = new char[lenSubStr * 2];
Не все классы, реализующие AutoCloseable, закрываются, либо закрываются корректно.
Для того, чтобы понять, реализует класс этот интерфейс, или нет, можно найти его на docs.oracle.com и в начале страницы документации посмотреть на All Implemented Interfaces.

2020-10-15 17:30 UTC, vlitomsk commented on task_1_2/src/main/java/Main.java
> +                int zArr[] = new int[str.length];
Выделение памяти в куче (в том числе и вызовом bufcat) -- дорогая операция. 
Предлагаю избавиться от лишних аллокаций.

2020-10-15 17:30 UTC, vlitomsk commented on task_1_2/src/main/java/Main.java
> +                int zArr[] = new int[str.length];
Также предлагаю сделать сплошной буфер одним участком памяти, а не два отдельных. Таким образом можно избавиться от bufcat.

2020-10-15 17:30 UTC, vlitomsk commented on task_1_2/src/main/java/Main.java
> +            System.out.println("IO Error: " + e);
Что, если пользователь в случае любых ошибок хочет завершать исполнение программы?
Предлагаю оставить обрабтку исключений пользователю этой функции.

2020-10-15 17:30 UTC, vlitomsk commented on task_1_2/src/main/java/Main.java
> +            char[] strForSearch = new char[lenSubStr * 2];
try-with-resources в помощь. Про это я писал в письме.

2020-10-15 17:30 UTC, vlitomsk commented on task_1_2/src/main/java/Main.java
> +    public static ArrayList<Long> substrSearchInFile (String fname, String substrIn) {
Предлагаю для универсальности функции сделать так, чтобы она принимала не путь до файла, а просто поток ввода. Таким образом можно будет подавать её не только файлы, но и строки, трубы, и вообще все что вписывается в концепцию потока ввода.

2020-10-15 17:30 UTC, vlitomsk commented on task_1_2/src/test/java/SearchTest.java
> +        // test 1
Предлагаю разбить это на отдельные тест-кейсы.
А то приходится думать, связан ли код двумя экранами ниже с тем, что двумя экранами выше.
Да хотя бы тесты внутри этой функции проверяют разное поведение целевой функции, например, 1. строчка найдена 2. строчка не найдена.

2020-10-15 17:30 UTC, vlitomsk commented on task_1_2/src/main/java/Main.java
> +                return resList;
Предлагаю эти два примера добавить в тестовый класс.
substr: abc
1. str: abcaabc
2. str: abcabcaabc

2020-10-15 17:30 UTC, vlitomsk commented on task_1_2/src/main/java/Main.java
> +                return resList;
смысл в том, что последние считанные символы могут быть суффиксом искомой строки.

2020-10-15 17:30 UTC, vlitomsk commented on task_1_2/src/main/java/Main.java
> +            readerq = new BufferedReader(new InputStreamReader(new FileInputStream(fname), StandardCharsets.UTF_8));
это не используется. надо удалить.

2020-10-15 17:30 UTC, vlitomsk commented on task_1_2/src/main/java/Main.java
> +                }
Заменить на более эффективную Sytem.arraycopy

2020-10-15 17:30 UTC, vlitomsk commented on task_1_2/src/main/java/Main.java
> +}
это после исправления замечаний не понадобится.

2020-10-15 17:30 UTC, vlitomsk commented on task_1_2/src/test/java/SearchTest.java
> +        BufferedWriter out4 = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(fname4), StandardCharsets.UTF_8));
А если в файле test4.txt лежат какие-то нужные данные? Может быть, его создал кто-то до нас?
Для таких целей обычно используются временные файлы. См. File.createTempFile

2020-10-15 17:30 UTC, vlitomsk commented on task_1_2/src/test/java/SearchTest.java
> +        BufferedWriter out5 = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(fname5), StandardCharsets.UTF_8));
try-with-resources.
и в других местах в этой функции тоже.

2020-10-16 12:37 UTC, vlitomsk commented on task_1_2/src/main/java/Main.java
> +                l2 = in.read(str, lenSubStr*2, lenSubStr);
А если под конец потока будет прочитано меньше байт, чем запрошено? (длина потока не кратна длине подстроки)

2020-10-16 12:37 UTC, vlitomsk commented on task_1_2/src/test/java/Search0Test.java
> +    public void substrSearchInStream() throws IOException {
можно было не создавать несколько классов под тест одной функции.
в одном классе может содержаться несколько @Test -методов.

2020-10-16 12:38 UTC, vlitomsk commented on task_1_2/src/test/java/Search0Test.java
> +    public void substrSearchInStream() throws IOException {
ну да ладно уже..

2020-10-16 12:38 UTC, vlitomsk requested changes
Вопрос по l2 = in.read(...)

2020-10-16 12:55 UTC, Sharapov-Maksim commented on task_1_2/src/main/java/Main.java
> +                l2 = in.read(str, lenSubStr*2, lenSubStr);
Если будет считано 0 байт, то встречен конец строки и в l2 вернётся -1. Если же считано меньше, чем запрошено, то символы, идущие после этих символов не изменятся, и произойдёт БАН. Сейчас поправлю)

2020-10-16 14:03 UTC, vlitomsk requested changes
Ок, принято!

2020-10-16 14:04 UTC, merged