First commit
Sharapov-Maksim/OOP_Sharapov_M pull request #3
Opened 2020-10-22 09:21 UTC by Sharapov-Maksim

First version of task

2020-10-22 17:58 UTC, vlitomsk requested changes
Замечания нужно исправить, на вопросы ответить %)

2020-10-22 17:58 UTC, vlitomsk commented on Task_2_1/src/main/java/Stack.java
> +                //if (!hasNext()) throw new IndexOutOfBoundsException("End of list.");\
Исключение хорошо бы выбросить, но в интерфейсе немного другое прописано: https://docs.oracle.com/javase/8/docs/api/java/util/Iterator.html#next--

2020-10-22 17:58 UTC, vlitomsk commented on Task_2_1/src/main/java/Stack.java
> +    public T pop () throws Exception{
Лучше в throws писать максимально конкретный класс.
Почему так лучше?

2020-10-22 17:58 UTC, vlitomsk commented on Task_2_1/src/test/java/StackTest.java
> +
Предлагаю добавить тест, проверяющий случай выталкивания элемента из пустого стека.
Для проверки того, что тест выбросил исключение, в junit есть специальная аннотация.

2020-10-22 17:58 UTC, vlitomsk commented on Task_2_1/src/test/java/StackTest.java
> +
Примеры тут есть: https://www.guru99.com/junit-annotations-api.html

2020-10-23 06:04 UTC, Sharapov-Maksim commented on Task_2_1/src/main/java/Stack.java
> +    public T pop () throws Exception{
Видимо так проще ловить и обрабатывать бросаемые исключения. Ведь в случае с throws Exception мы лишь даём  информацию, что что-то может пойти не так, но не конкретные исключения.

2020-10-23 19:47 UTC, vlitomsk requested changes
ОК принято

2020-10-23 19:48 UTC, merged